/*
 * Copyright 2019 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _LED_H_
#define _LED_H_

#define Example_Num 12
#if Example_Num==12
extern uint16_t EXAMPLE_LEDdata[12];
#elif Example_Num==2
extern uint16_t EXAMPLE_LEDdata[2];
#endif

#define LED_LPSPI_MASTER_BASEADDR (LPSPI6)
#define LED_LPSPI_MASTER_CLK_FREQ (CLOCK_GetFreqFromObs(CCM_OBS_LPSPI6_CLK_ROOT))
#define LED_LPSPI_TRANSFER_BAUDRATE 50000U 

#define APP_SPI_LED_RCK_GPIO GPIO12
#define APP_SPI_LED_RCK_PIN  12U

#define APP_SPI_LED_CLR_GPIO GPIO12
#define APP_SPI_LED_CLR_PIN  13U

#define APP_SPI_LED_G_GPIO GPIO12
#define APP_SPI_LED_G_PIN  9U

#define CoreClock_Hz (CLOCK_GetCpuClkFreq())

void LED_SPI_InitPins(void);
void LED_SpiInitHardware(void);
void LED_InitHardware(void);
void RCK_Toggle(void);
void LED_Write(uint16_t *led_data);
void RCK_Toggle(void);
void SPICS_Control(bool enable);
void LED_SpiInit(void);

#endif /* _LED_H_ */
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
