/*
 * Copyright 2019 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v7.0
processor: MIMXRT1176xxxxx
package_id: MIMXRT1176DVMAA
mcu_data: ksdk2_0
processor_version: 0.0.0
pin_labels:
- {pin_num: M13, pin_signal: GPIO_AD_04, label: USER_LED, identifier: USER_LED}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
    BOARD_InitPins();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm7, enableClock: 'true'}
- pin_list:
  - {pin_num: L13, peripheral: LPUART1, signal: TXD, pin_signal: GPIO_AD_24, software_input_on: Disable, pull_up_down_config: Pull_Down, pull_keeper_select: Keeper,
    open_drain: Disable, drive_strength: High, slew_rate: Slow}
  - {pin_num: M15, peripheral: LPUART1, signal: RXD, pin_signal: GPIO_AD_25, software_input_on: Disable, pull_up_down_config: Pull_Down, pull_keeper_select: Keeper,
    open_drain: Disable, drive_strength: High, slew_rate: Slow}
  - {pin_num: M13, peripheral: GPIO9, signal: 'gpio_io, 03', pin_signal: GPIO_AD_04, direction: OUTPUT, gpio_init_state: 'false', software_input_on: Disable, pull_up_down_config: Pull_Down,
    pull_keeper_select: Keeper, open_drain: Disable, drive_strength: High, slew_rate: Slow}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* LPCG on: LPCG is ON. */

  /* GPIO configuration of USER_LED on GPIO_EMC_B2_19 (pin U2) */
  gpio_pin_config_t USER_LED_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_B2_19 (pin U2) */
  GPIO_PinInit(GPIO8, 29U, &USER_LED_config);

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_EMC_B2_19_GPIO8_IO29,       /* GPIO_EMC_B2_19 is configured as GPIO8_IO29 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_03_GPIO9_IO02,           /* GPIO_AD_03 is configured as GPIO9_IO02 for SD Card insert detect */
      0U);
  
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_LPSR_04_LPUART11_TXD,       /* GPIO_LPSR_04 is configured as LPUART1_TXD */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_LPSR_05_LPUART11_RXD,       /* GPIO_LPSR_05 is configured as LPUART1_RXD */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B1_00_USDHC1_CMD,        /* GPIO_SD_B1_00 is configured as USDHC1_CMD */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_SD_B1_00 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B1_01_USDHC1_CLK,        /* GPIO_SD_B1_01 is configured as USDHC1_CLK */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_SD_B1_01 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B1_02_USDHC1_DATA0,      /* GPIO_SD_B1_02 is configured as USDHC1_DATA0 */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_SD_B1_02 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B1_03_USDHC1_DATA1,      /* GPIO_SD_B1_03 is configured as USDHC1_DATA1 */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_SD_B1_03 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B1_04_USDHC1_DATA2,      /* GPIO_SD_B1_04 is configured as USDHC1_DATA2 */
      1U);                                    /* Software Input On Field: Force input path of pad GPIO_SD_B1_04 */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_SD_B1_05_USDHC1_DATA3,      /* GPIO_SD_B1_05 is configured as USDHC1_DATA3 */
      1U);

  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_EMC_B2_19_GPIO8_IO29,       /* GPIO_EMC_B2_19 PAD functional properties : */
      0x02U);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_LPSR_04_LPUART11_TXD,       /* GPIO_LPSR_04 PAD functional properties : */
      0x02U);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_LPSR_05_LPUART11_RXD,        /* GPIO_LPSR_05 PAD functional properties : */
      0x02U);                                 /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: high driver
                                                 Pull / Keep Select Field: Pull Disable, Highz
                                                 Pull Up / Down Config. Field: Weak pull down
                                                 Open Drain Field: Disabled */
												 
  
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_00_GPIO8_IO31, 0U); /* GPIO_AD_00 is configured as RESET */
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_02_GPIO9_IO01, 0U); /* GPIO_AD_02 is configured as STBYB */
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_B2_18_GPIO8_IO28, 0U); /* GPIO_EMC_B2_18 is configured as Backlight_CTL */
  IOMUXC_SetPinMux(IOMUXC_GPIO_LPSR_09_GPIO12_IO09, 0U);  /* GPIO_LPSR_09 is configured as Backlight_EN */

  IOMUXC_SetPinMux(IOMUXC_GPIO_DISP_B1_00_VIDEO_MUX_LCDIF_CLK, 0U);      /* GPIO_DISP_B1_00 is configured as LCD_CLK */
  IOMUXC_SetPinMux(IOMUXC_GPIO_DISP_B1_01_VIDEO_MUX_LCDIF_ENABLE, 0U);   /* GPIO_DISP_B1_01 is configured as LCD_ENABLE */
  IOMUXC_SetPinMux(IOMUXC_GPIO_DISP_B1_02_VIDEO_MUX_LCDIF_HSYNC, 0U);    /* GPIO_DISP_B1_02 is configured as LCD_HSYNC */
  IOMUXC_SetPinMux(IOMUXC_GPIO_DISP_B1_03_VIDEO_MUX_LCDIF_VSYNC, 0U);    /* GPIO_DISP_B1_03 is configured as LCD_VSYNC */
  IOMUXC_SetPinMux(IOMUXC_GPIO_DISP_B1_04_VIDEO_MUX_LCDIF_DATA00, 0U);   /* GPIO_DISP_B1_04 is configured as LCD_DATA00 */
  IOMUXC_SetPinMux(IOMUXC_GPIO_DISP_B1_05_VIDEO_MUX_LCDIF_DATA01, 0U);   /* GPIO_DISP_B1_05 is configured as LCD_DATA01 */
  IOMUXC_SetPinMux(IOMUXC_GPIO_DISP_B1_06_VIDEO_MUX_LCDIF_DATA02, 0U);   /* GPIO_DISP_B1_06 is configured as LCD_DATA02 */
  IOMUXC_SetPinMux(IOMUXC_GPIO_DISP_B1_07_VIDEO_MUX_LCDIF_DATA03, 0U);   /* GPIO_DISP_B1_07 is configured as LCD_DATA03 */
  IOMUXC_SetPinMux(IOMUXC_GPIO_DISP_B1_08_VIDEO_MUX_LCDIF_DATA04, 0U);   /* GPIO_DISP_B1_08 is configured as LCD_DATA04 */
  IOMUXC_SetPinMux(IOMUXC_GPIO_DISP_B1_09_VIDEO_MUX_LCDIF_DATA05, 0U);   /* GPIO_DISP_B1_09 is configured as LCD_DATA05 */
  IOMUXC_SetPinMux(IOMUXC_GPIO_DISP_B1_10_VIDEO_MUX_LCDIF_DATA06, 0U);   /* GPIO_DISP_B1_10 is configured as LCD_DATA06 */
  IOMUXC_SetPinMux(IOMUXC_GPIO_DISP_B1_11_VIDEO_MUX_LCDIF_DATA07, 0U);   /* GPIO_DISP_B1_11 is configured as LCD_DATA07 */
  IOMUXC_SetPinMux(IOMUXC_GPIO_DISP_B2_00_VIDEO_MUX_LCDIF_DATA08, 0U);   /* GPIO_DISP_B2_00 is configured as LCD_DATA08 */
  IOMUXC_SetPinMux(IOMUXC_GPIO_DISP_B2_01_VIDEO_MUX_LCDIF_DATA09, 0U);   /* GPIO_DISP_B2_01 is configured as LCD_DATA09 */
  IOMUXC_SetPinMux(IOMUXC_GPIO_DISP_B2_02_VIDEO_MUX_LCDIF_DATA10, 0U);   /* GPIO_DISP_B2_02 is configured as LCD_DATA10 */
  IOMUXC_SetPinMux(IOMUXC_GPIO_DISP_B2_03_VIDEO_MUX_LCDIF_DATA11, 0U);   /* GPIO_DISP_B2_03 is configured as LCD_DATA11 */
  IOMUXC_SetPinMux(IOMUXC_GPIO_DISP_B2_04_VIDEO_MUX_LCDIF_DATA12, 0U);   /* GPIO_DISP_B2_04 is configured as LCD_DATA12 */
  IOMUXC_SetPinMux(IOMUXC_GPIO_DISP_B2_05_VIDEO_MUX_LCDIF_DATA13, 0U);   /* GPIO_DISP_B2_05 is configured as LCD_DATA13 */
  IOMUXC_SetPinMux(IOMUXC_GPIO_DISP_B2_06_VIDEO_MUX_LCDIF_DATA14, 0U);   /* GPIO_DISP_B2_06 is configured as LCD_DATA14 */
  IOMUXC_SetPinMux(IOMUXC_GPIO_DISP_B2_07_VIDEO_MUX_LCDIF_DATA15, 0U);   /* GPIO_DISP_B2_07 is configured as LCD_DATA15 */
  IOMUXC_SetPinMux(IOMUXC_GPIO_DISP_B2_08_VIDEO_MUX_LCDIF_DATA16, 0U);   /* GPIO_DISP_B2_08 is configured as LCD_DATA16 */
  IOMUXC_SetPinMux(IOMUXC_GPIO_DISP_B2_09_VIDEO_MUX_LCDIF_DATA17, 0U);   /* GPIO_DISP_B2_09 is configured as LCD_DATA17 */
  IOMUXC_SetPinMux(IOMUXC_GPIO_DISP_B2_10_VIDEO_MUX_LCDIF_DATA18, 0U);   /* GPIO_DISP_B2_10 is configured as LCD_DATA18 */
  IOMUXC_SetPinMux(IOMUXC_GPIO_DISP_B2_11_VIDEO_MUX_LCDIF_DATA19, 0U);   /* GPIO_DISP_B2_11 is configured as LCD_DATA19 */
  IOMUXC_SetPinMux(IOMUXC_GPIO_DISP_B2_12_VIDEO_MUX_LCDIF_DATA20, 0U);   /* GPIO_DISP_B2_12 is configured as LCD_DATA20 */
  IOMUXC_SetPinMux(IOMUXC_GPIO_DISP_B2_13_VIDEO_MUX_LCDIF_DATA21, 0U);   /* GPIO_DISP_B2_13 is configured as LCD_DATA21 */
  IOMUXC_SetPinMux(IOMUXC_GPIO_DISP_B2_14_VIDEO_MUX_LCDIF_DATA22, 0U);   /* GPIO_DISP_B2_14 is configured as LCD_DATA22 */
  IOMUXC_SetPinMux(IOMUXC_GPIO_DISP_B2_15_VIDEO_MUX_LCDIF_DATA23, 0U);   /* GPIO_DISP_B2_15 is configured as LCD_DATA23 */

  IOMUXC_SetPinConfig(IOMUXC_GPIO_DISP_B1_00_VIDEO_MUX_LCDIF_CLK, 4U);             /* GPIO_B0_00 PAD functional properties : */
  IOMUXC_SetPinConfig(IOMUXC_GPIO_DISP_B1_01_VIDEO_MUX_LCDIF_ENABLE, 4U);          /* GPIO_B0_01 PAD functional properties : */
  IOMUXC_SetPinConfig(IOMUXC_GPIO_DISP_B1_02_VIDEO_MUX_LCDIF_HSYNC, 4U);           /* GPIO_B0_02 PAD functional properties : */
  IOMUXC_SetPinConfig(IOMUXC_GPIO_DISP_B1_03_VIDEO_MUX_LCDIF_VSYNC, 4U);           /* GPIO_B0_03 PAD functional properties : */
  IOMUXC_SetPinConfig(IOMUXC_GPIO_DISP_B1_04_VIDEO_MUX_LCDIF_DATA00,4U);           /* GPIO_B0_04 PAD functional properties : */
  IOMUXC_SetPinConfig(IOMUXC_GPIO_DISP_B1_05_VIDEO_MUX_LCDIF_DATA01, 4U);
  IOMUXC_SetPinConfig(IOMUXC_GPIO_DISP_B1_06_VIDEO_MUX_LCDIF_DATA02, 4U);    
  IOMUXC_SetPinConfig(IOMUXC_GPIO_DISP_B1_07_VIDEO_MUX_LCDIF_DATA03, 4U);       
  IOMUXC_SetPinConfig(IOMUXC_GPIO_DISP_B1_08_VIDEO_MUX_LCDIF_DATA04, 4U);       
  IOMUXC_SetPinConfig(IOMUXC_GPIO_DISP_B1_09_VIDEO_MUX_LCDIF_DATA05, 4U);         
  IOMUXC_SetPinConfig(IOMUXC_GPIO_DISP_B1_10_VIDEO_MUX_LCDIF_DATA06, 4U);        
  IOMUXC_SetPinConfig(IOMUXC_GPIO_DISP_B1_11_VIDEO_MUX_LCDIF_DATA07, 4U);         
  IOMUXC_SetPinConfig(IOMUXC_GPIO_DISP_B2_00_VIDEO_MUX_LCDIF_DATA08, 4U);       
  IOMUXC_SetPinConfig(IOMUXC_GPIO_DISP_B2_01_VIDEO_MUX_LCDIF_DATA09, 4U);        
  IOMUXC_SetPinConfig(IOMUXC_GPIO_DISP_B2_02_VIDEO_MUX_LCDIF_DATA10, 4U);         
  IOMUXC_SetPinConfig(IOMUXC_GPIO_DISP_B2_03_VIDEO_MUX_LCDIF_DATA11, 4U);         
  IOMUXC_SetPinConfig(IOMUXC_GPIO_DISP_B2_04_VIDEO_MUX_LCDIF_DATA12, 4U);      
  IOMUXC_SetPinConfig(IOMUXC_GPIO_DISP_B2_05_VIDEO_MUX_LCDIF_DATA13, 4U);        
  IOMUXC_SetPinConfig(IOMUXC_GPIO_DISP_B2_06_VIDEO_MUX_LCDIF_DATA14, 4U);          
  IOMUXC_SetPinConfig(IOMUXC_GPIO_DISP_B2_07_VIDEO_MUX_LCDIF_DATA15, 4U);          
  IOMUXC_SetPinConfig(IOMUXC_GPIO_DISP_B2_08_VIDEO_MUX_LCDIF_DATA16, 4U);
  IOMUXC_SetPinConfig(IOMUXC_GPIO_DISP_B2_09_VIDEO_MUX_LCDIF_DATA17, 4U);
  IOMUXC_SetPinConfig(IOMUXC_GPIO_DISP_B2_10_VIDEO_MUX_LCDIF_DATA18, 4U);
  IOMUXC_SetPinConfig(IOMUXC_GPIO_DISP_B2_11_VIDEO_MUX_LCDIF_DATA19, 4U);
  IOMUXC_SetPinConfig(IOMUXC_GPIO_DISP_B2_12_VIDEO_MUX_LCDIF_DATA20, 4U);
  IOMUXC_SetPinConfig(IOMUXC_GPIO_DISP_B2_13_VIDEO_MUX_LCDIF_DATA21, 4U);
  IOMUXC_SetPinConfig(IOMUXC_GPIO_DISP_B2_14_VIDEO_MUX_LCDIF_DATA22, 4U);
  IOMUXC_SetPinConfig(IOMUXC_GPIO_DISP_B2_15_VIDEO_MUX_LCDIF_DATA23, 4U);


IOMUXC_SetPinConfig(
      IOMUXC_GPIO_SD_B1_00_USDHC1_CMD,        /* GPIO_SD_B1_00 PAD functional properties : */
      0x04U);                                 /* PDRV Field: high driver
                                                 Pull Down Pull Up Field: PU
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_SD_B1_01_USDHC1_CLK,        /* GPIO_SD_B1_01 PAD functional properties : */
      0x04U);                                 /* PDRV Field: high driver
                                                 Pull Down Pull Up Field: PU
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_SD_B1_02_USDHC1_DATA0,      /* GPIO_SD_B1_02 PAD functional properties : */
      0x04U);                                 /* PDRV Field: high driver
                                                 Pull Down Pull Up Field: PU
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_SD_B1_03_USDHC1_DATA1,      /* GPIO_SD_B1_03 PAD functional properties : */
      0x04U);                                 /* PDRV Field: high driver
                                                 Pull Down Pull Up Field: PU
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_SD_B1_04_USDHC1_DATA2,      /* GPIO_SD_B1_04 PAD functional properties : */
      0x04U);                                 /* PDRV Field: high driver
                                                 Pull Down Pull Up Field: PU
                                                 Open Drain Field: Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_SD_B1_05_USDHC1_DATA3,      /* GPIO_SD_B1_05 PAD functional properties : */
      0x04U);                                 /* PDRV Field: high driver
                                                 Pull Down Pull Up Field: PU
                                                 Open Drain Field: Disabled */

}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
